spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  batch:
    initialize-schema: always
    job:
      enabled: true
      name: creditRiskAnalysisJob
    chunk-size: 100
    max-threads: 4
    retry-policy:
      max-attempts: 3
      backoff:
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

server:
  port: 8080

app:
  batch:
    input:
      file: classpath:input/credit-risk-data.csv
    output:
      file: file:./output/credit-risk-results.csv
    risk:
      thresholds:
        low: 700
        medium: 600
        high: 500
      weights:
        credit-score: 0.4
        income: 0.2
        debt-ratio: 0.2
        payment-history: 0.2

logging:
  level:
    root: INFO
    org.springframework.batch: DEBUG
    com.example.creditrisk: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/credit-risk-batch.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
